# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python 3.13
      run: |
        sudo apt update
        sudo apt install -y wget build-essential
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tar.xz
        tar -xf Python-3.13.0.tar.xz
        cd Python-3.13.0
        ./configure --enable-optimizations
        make -j $(nproc)
        sudo make altinstall
        python3.13 -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python3.13 -m pip install flake8 pytest
        if [ -f requirements.txt ]; then python3.13 -m pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        python3.13 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python3.13 -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        python3.13 -m pytestt
